### ISSUE TITLE
Extension failed on macOS

### ISSUE THREAD

**Issue by zaq42** [dotenv-org/dotenv-vscode#29]
macOS Monterey: 12.5.1
VSCode: Version: 1.71.2 (Universal)
Extension: dotenv.dotenv-vscode v0.9.0 Last updated 11/Sep/2022, 07:08:26

Here's the error from the Extension Host log:

```[2022-09-19 11:28:15.765] [exthost] [info] ExtensionService#_doActivateExtension dotenv.dotenv-vscode, startup: false, activationEvent: '*'
[2022-09-19 11:28:15.770] [exthost] [error] Activating extension dotenv.dotenv-vscode failed due to an error:
[2022-09-19 11:28:15.770] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'textMateRules')
    at hideValues (/Users/Dave/.vscode/extensions/dotenv.dotenv-vscode-0.9.0/lib/autocloaking.js:24:24)
    at Object.run (/Users/Dave/.vscode/extensions/dotenv.dotenv-vscode-0.9.0/lib/autocloaking.js:7:5)
    at activate (/Users/Dave/.vscode/extensions/dotenv.dotenv-vscode-0.9.0/extension.js:9:16)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17649)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17307)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:15118
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at E._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8224)
    at E._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8166)
    at E._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7530)
```
In my config, I didn't appear to have a setting named `textMateRules`.  (It may not have been mac specific.)

### Workaround
I was able to get it working by adding this block to my User settings.json and reinstalling the extension
```    
"editor.tokenColorCustomizations": {
     "textMateRules": []
 }
```

**Comment by Acestriker** [comment]
I'm having the same issue.
Could you post the path to the user settings.json? Confused as to where to add that string.

**Comment by zaq42** [comment]
@Acestriker, the easy way is to use View → Command Palette... and search for `Preferences: Open User Settings (JSON)`

That's the file I changed, probably something like `...Library/Application Support/Code/User/settings.json`.

Just add the entry I quoted inside the root level braces; Probably easiest to put it at the end, you'll need to make sure there's a comma after the previous line.

``` 
{ 
    ...
    "some.other.config": [
        ...
    ],
    "editor.tokenColorCustomizations": {
        "textMateRules": []
    }
}

**Comment by Acestriker** [comment]
@zaq42, thanks for that ❤️. I'm new to VSC (coming from Eclipse) and the command palette is foreign to me.

**Comment by motdotla** [comment]
Thank you for raising this. Will get fixed as soon as possible.

**Comment by motdotla** [comment]
I was able to duplicate this.

`0.11.0` fixes the problem. Uninstall and re-install the latest and you should be good to go.

https://marketplace.visualstudio.com/items?itemName=dotenv.dotenv-vscode

**Comment by nicolashenry** [comment]
@motdotla I have the same issue on Windows using v0.23.0, the workaround still works though.

**Comment by dragon-fish** [comment]
@motdotla Apr 19 2023 - Still have the same issue on Windows.

```
[2023-04-19 14:58:42.299] [exthost] [error] TypeError: Cannot set properties of undefined (setting 'textMateRules')
    at unhideValues (<user>\.vscode\extensions\dotenv.dotenv-vscode-0.23.0\lib\autocloaking.js:76:23)
    at dotenvToggleAutocloaking (<user>\.vscode\extensions\dotenv.dotenv-vscode-0.23.0\lib\autocloaking.js:141:5)
    at <user>\.vscode\extensions\dotenv.dotenv-vscode-0.23.0\lib\autocloaking.js:17:105
    at a._executeContributedCommand (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63922)
    at a.$executeContributedCommand (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:64626)
    at o._doInvokeHandler (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13691)
    at o._invokeHandler (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13373)
    at o._receiveRequest (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12143)
    at o._receiveOneMessage (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10845)
    at <user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8952
    at w.invoke (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
    at <user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:17079
    at w.invoke (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
    at i._receiveMessage (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23593)
    at <user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21127
    at w.invoke (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at p.acceptChunk (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15837)
    at <user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:14967
    at Socket.l (<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:26303)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) dotenv.toggleAutocloaking {"value":"dotenv.dotenv-vscode","_lower":"dotenv.dotenv-vscode"}
```
